### ISSUE TITLE
Strange Text Color Behavior in Quizzes with Dark Appearance

### ISSUE THREAD

**Issue by kittyconfusion** [adrWasTaken/CanvasPlus#9]
When not selecting a textbox during a quiz, the contents of the textbox will be black text on a white background. This is the same as it would normally appear without Canvas+. All other textboxes besides the one selected will appear this way.
![image](https://user-images.githubusercontent.com/65476906/117588115-0a334c00-b0e7-11eb-89bc-963d5a05c606.png)

When selecting a textbox during a quiz, text will appear as expected with Canvas+, however any equations inputted will appear as black text on a black background. This makes them difficult to make out. Note that in the actual equation editor it appears as expected with white on black.
![image](https://user-images.githubusercontent.com/65476906/117588125-15867780-b0e7-11eb-9e2a-f813a4c33bbd.png)

**Comment by J-Coding-Dev** [comment]
I looked into the code and attempted to fix this, but it turns out that the equations are images, so they cannot be modified with css. There may be a way to do this, but it would require a lot of work.

**Comment by adrWasTaken** [comment]
I'll be working on a fix to this! @J-Coding-Dev if you want to try it yourself, a CSS `filter: invert` may be the solution.

**Comment by J-Coding-Dev** [comment]
This should work
.equation_image {
  filter: invert(100%)
}

**Comment by adrWasTaken** [comment]
Fixed in version 0.2.2
